export const editStrings = [
  "I love ice cream.",
  "I hate beer.",
  "My favorite color is blue.",
  "I enjoy reading books.",
  "I like to go hiking.",
  "My favorite movie is Inception.",
  "I enjoy playing video games.",
  "I like to travel.",
  "I'm learning to play the guitar.",
  "I enjoy cooking.",
  "I love listening to music.",
  "I enjoy watching the sunset.",
  "I like to explore new places.",
  "I find joy in reading a good book.",
  "I appreciate a good cup of coffee.",
  "I enjoy spending time with my friends.",
  "I like learning new things.",
  "I find peace in long walks.",
  "I enjoy the sound of rain.",
  "I love the smell of fresh bread.",
  "random string 1",
  "random string 2",
  "I like watching movies.",
  "I enjoy learning new languages.",
  "I love painting.",
  "I find joy in gardening.",
  "I like baking cookies.",
  "I enjoy swimming in the ocean.",
  "My favorite hobby is photography.",
  "I like playing chess.",
  "I enjoy going to the gym.",
  "I love spending time with family.",
  "I like riding my bike.",
  "I enjoy writing stories.",
  "My favorite sport is basketball.",
  "I like solving puzzles.",
  "I enjoy camping in the mountains.",
  "I love taking nature walks.",
  "I like listening to podcasts.",
  "I enjoy doing yoga.",
  "My favorite season is autumn.",
  "I like playing board games.",
  "I enjoy star gazing.",
  "I love watching documentaries.",
  "I like making crafts.",
  "I enjoy attending concerts.",
  "My favorite food is sushi.",
  "I like trying new restaurants.",
  "I enjoy going to the beach.",
  "I love practicing mindfulness.",
  "I like learning about history.",
  "I enjoy playing the piano.",
  "My favorite drink is tea.",
  "I like volunteering in my community.",
  "I enjoy visiting museums.",
  "I love taking road trips.",
  "I like working on DIY projects.",
  "I enjoy playing with my pets.",
  "My favorite dessert is cheesecake.",
  "I like listening to audiobooks.",
  "I enjoy doing crossword puzzles.",
  "I love spending time in nature.",
  "I like visiting art galleries.",
  "I enjoy attending theater plays.",
  "My favorite flower is the sunflower.",
  "I like practicing meditation.",
  "I enjoy cooking new recipes.",
  "I love exploring national parks.",
  "I like collecting stamps.",
  "I enjoy attending festivals.",
  "My favorite tree is the oak.",
  "I like gardening in my backyard.",
  "I enjoy learning new skills.",
  "I love making pottery.",
  "I like watching wildlife.",
  "I enjoy going to farmers markets.",
  "My favorite animal is the dolphin.",
  "I like playing tennis.",
  "I enjoy going on picnics.",
  "I love watching the stars.",
  "I like bird watching.",
  "I enjoy making jewelry.",
  "My favorite place is the mountains.",
  "I like trying new hobbies.",
  "I enjoy going on adventures.",
  "I love sailing on the lake.",
  "I like attending sports events.",
  "I enjoy taking dance classes.",
  "My favorite book is Pride and Prejudice.",
  "I like doing photography walks.",
  "I enjoy visiting historical sites.",
  "I love learning about astronomy.",
  "I like playing with children.",
  "I enjoy taking bubble baths.",
  "My favorite band is The Beatles.",
  "I like creating digital art.",
  "I enjoy practicing archery.",
  "I love watching animated movies.",
  "I like doing science experiments.",
  "I enjoy learning about marine life.",
  "My favorite snack is popcorn.",
  "I like building model airplanes.",
  "I enjoy doing tai chi.",
  "I love attending wine tastings.",
  "I like knitting scarves.",
  "I enjoy going to amusement parks.",
  "My favorite TV show is Friends.",
  "I like making homemade gifts.",
  "I enjoy exploring caves.",
  "I love listening to classical music.",
  "I like making soap.",
  "I enjoy trying new cuisines.",
  "My favorite superhero is Spider-Man.",
  "I like going to book clubs.",
  "I enjoy doing escape rooms.",
  "I love learning about different cultures.",
  "I like practicing calligraphy.",
  "I enjoy attending art workshops.",
  "My favorite fruit is mango.",
  "I like making candles.",
  "I enjoy playing frisbee.",
  "I love visiting botanical gardens.",
  "I like going to the zoo.",
  "I enjoy watching ballet.",
  "I like practicing magic tricks.",
  "I enjoy rock climbing.",
  "I love learning about physics.",
  "I like doing community service.",
  "I enjoy making flower arrangements.",
  "My favorite comedian is Robin Williams.",
  "I like doing woodwork.",
  "I enjoy going on nature hikes.",
  "I love listening to jazz.",
  "I like playing with Legos.",
  "I enjoy attending live shows.",
  "My favorite instrument is the violin.",
  "I like learning new software.",
  "I enjoy doing pottery classes.",
  "I love participating in trivia nights.",
  "I like going to the planetarium.",
  "I enjoy learning about geology.",
  "My favorite holiday is Christmas.",
  "I like watching foreign films.",
  "I enjoy writing poetry.",
  "I love exploring abandoned places.",
  "I like practicing martial arts.",
  "I enjoy doing mindfulness exercises.",
  "I love learning about space exploration.",
  "I like going to flea markets.",
  "I enjoy collecting vintage items.",
  "My favorite painter is Van Gogh.",
  "I like making origami.",
  "I enjoy going to car shows.",
  "I love learning about ancient civilizations.",
  "I like watching magic shows.",
  "I enjoy doing jigsaw puzzles.",
  "My favorite vegetable is broccoli.",
  "I like attending science fairs.",
  "I enjoy playing card games.",
  "I love visiting aquariums.",
  "I like practicing playing drums.",
  "I enjoy making scrapbooks.",
  "My favorite poet is Robert Frost.",
  "I like visiting bookstores.",
  "I enjoy doing improv comedy.",
  "I love learning about psychology.",
  "I like attending lectures.",
  "I enjoy going on scenic drives.",
  "My favorite cuisine is Italian.",
  "I like creating comic strips.",
  "I enjoy going to the opera.",
  "I love watching musicals.",
  "I like practicing parkour.",
  "I enjoy learning about architecture.",
  "My favorite drink is hot chocolate.",
  "I like attending workshops.",
  "I enjoy playing darts.",
  "I love exploring forests.",
  "I like learning about meteorology.",
  "I enjoy going to the circus.",
  "My favorite gemstone is sapphire.",
  "I like practicing public speaking.",
  "I enjoy doing charity work.",
  "I love watching wildlife documentaries.",
  "I like learning about mythology.",
  "I enjoy doing metalworking.",
  "My favorite planet is Saturn.",
  "I like creating graphic designs.",
  "I enjoy going to comedy clubs.",
  "I love learning about economics.",
  "I like making quilts.",
  "I enjoy going to music festivals.",
  "My favorite sculpture is The Thinker.",
  "I like practicing yoga.",
  "I enjoy attending cultural festivals.",
  "I love learning about world history.",
  "I like visiting libraries.",
  "I enjoy doing voice acting.",
  "My favorite dance is the tango.",
  "I like making paper crafts.",
  "I enjoy going to food tastings.",
  "I love learning about anthropology.",
  "I like attending art exhibitions.",
  "I enjoy going to street fairs.",
  "My favorite insect is the butterfly.",
  "I like creating video content.",
  "I enjoy participating in hackathons.",
];
